# This is the default configuration of the exporter and is baked into the
# executable at build time. It configures the default values for all parameters.
web:
  telemetry_path: /metrics
  read_header_timeout: 1s
  listen:
    - tcp://[::]:9115
  auth:
    basic_auth: []

collector:
  max_connections: 50

host_defaults:
  poll_frequency: 30s
  disable_ping: false
  ping_timeout: 1s
  ping_count: 3

  service_defaults:
    timeout: 10s
    proxy: direct
    max_bytes: 4096
    tls_cacerts:
      - system
    http_enable_redirects: false
    http_max_redirects: 10

hosts: []