- system
# Certificates can either be a file...
- test_data/tls_cacerts/some.crt
# Or specified as inline strings
- |
  -----BEGIN CERTIFICATE-----
  MIIFVDCCAzygAwIBAgIIFwhjFyf7F+cwDQYJKoZIhvcNAQELBQAwPDEVMBMGA1UE
  BhMMVGVzdCBDb3VudHJ5MREwDwYDVQQKEwhUZXN0IE9yZzEQMA4GA1UECxMHVGVz
  dCBPVTAeFw0yMjA4MDUwNzQzMzNaFw0yMzA4MDUxMzQzMzNaMDwxFTATBgNVBAYT
  DFRlc3QgQ291bnRyeTERMA8GA1UEChMIVGVzdCBPcmcxEDAOBgNVBAsTB1Rlc3Qg
  T1UwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDB8F5vfTP+7fsC/AMv
  UlPCjLtFAzThtZAO1wy2sjhYTg1srBb6iUQgxSrPVuXxmaWEhQxXmouQQZw/FcXB
  xcuB22TstfDydleVnR5BT7QFxgLS3YcTA130kRptZY2Zv8H75/fc+dA0NC7pFhLF
  8S4Lof41MhYwb9qBLR8aYJKqgJCIAjQ1r6eHK+dMPXEYODzFeUdRCV5K5UCUAc41
  cZc/dR2bVN6iJAyIHCI3qTfDJHgHWTsEVZB1NKnM3wACksaetDJtSZJ042jyeG7H
  L92aSvI74V0HNPhids99hqTgTDRbfzPglRNTprWqVWldZpfgvhy3GxkicfpI/KWJ
  yUCNfNrucd1xaWrdoyAwENf2qMiYHRdAtOgYhU7AtGTpUoRLmjT8OfWd25fErIbd
  RB7NEdWeC3Sd6/F1Lgvo4QvOWD2eszEjvfVhFZcXarnz/u64PBEEVtUihb7ZN2X1
  bZyiyWZGWVsFcnB9LDIAIIq2FUKW9Imlj4J1PD9gZKpNqnCnSA1CHjcCqRk/BMJC
  UBV9FVNJzMtVQ2sKCfGB85BmrcQxl1RDIzY78BVFhAT6IBIPQCHPTgFoHKbkL/7H
  uHOit40u/zogoNEqMxbJD9DYeqHFSILnFjg4pobMkadMyg164FekUGVVtGkBgAIl
  pFM7IzdYvHS8rev1OgvsK2yEvQIDAQABo1owWDAOBgNVHQ8BAf8EBAMCAqQwHQYD
  VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wFgYD
  VR0RBA8wDYIAgQl0ZXN0QHRlc3QwDQYJKoZIhvcNAQELBQADggIBAAGlB8/1A6Ab
  kB2plUkGNenXLgnZE9ARQmPyS967TM6eis5CfX+BQKO8++sZvuYXF2JXggN1ppNA
  C+fKrLZvu+Umh55ZNY3PcWkOxsveHWEEBCIpKfkZ3NPG08tJiHrsRyx+w0162mAT
  SoKP8Yqa3GEU2DecJyOh01LTk43k2yIsnvI31V5kOxbbJk5kSYjCrnZnkcaWdCnX
  +QY18u6stxGvxYVheZH5pqaXxWqaeUl8d0ZshByqY5qQybVG/rH9fN62zgALPzLo
  tTc8M+GIEf3F7cf1XFKPisN3sbTPQ7cgNRfw47kp3cGbJnXNwNvAVou/gAEUdoZt
  l/60oHw5I5cIEemZDqGA9jNTiJYO4qP2oCImcSmOyHgTHoA8nCWhUike7vuWJC/Y
  1reGuKqGNxTrbht2PcMWnKLpa/CioY2i0WKcIKSu5q3dZHwuyYNkjGvw2PHIExlH
  zM8y+JSZ6W5pJV4fYDbXf2oLNE4ciVQ7pp9/7vTzAA+O7OqY9x13wz9gDGFGw7lk
  Rm7xmzFg7uoLCEuRWr3rKSdOAUtCfB6QoeUwQsZGl5cn4+if8oSIqaE9C02y00Nx
  aUnQ0iNzuc9uQlRkYs3wOJhJL5Y88ETjqVA4TfPn4l+HBzjwKIpR+Nz3OSrHmecz
  qLoWk4doiOYDT/kT5Vlq+Ldwmt408H53
  -----END CERTIFICATE-----